const mongoose = require("mongoose");

// One grading record per field-staff user per period (e.g. one per month).
// Auto-generated by the grading engine, but an admin can override any score.
const gradeSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    role: { type: String, enum: ["awc", "sector"], required: true }, // grading applies to field staff only

    districtCode: { type: String, required: true, index: true },
    blockCode: { type: String, index: true },
    sectorCode: { type: String, index: true },
    awcCode: { type: String, index: true },

    period: { type: String, required: true, index: true }, // "YYYY-MM"

    // Sub-scores, each 0-100
    punctualityScore: { type: Number, default: 0 },
    submissionQualityScore: { type: Number, default: 0 },
    beneficiaryRatioScore: { type: Number, default: 0 },
    taskCompletionScore: { type: Number, default: 0 },
    supervisorRemarksScore: { type: Number, default: 0 },

    totalScore: { type: Number, default: 0 }, // weighted average of the above
    grade: { type: String, enum: ["A", "B", "C", "D"] }, // bucketed from totalScore

    supervisorRemarks: { type: String },

    isAutoGenerated: { type: Boolean, default: true },
    generatedAt: { type: Date, default: Date.now },
    lastEditedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }, // set when an admin manually overrides
  },
  { timestamps: true }
);

// One grade document per user per period
gradeSchema.index({ user: 1, period: 1 }, { unique: true });

module.exports = mongoose.model("Grade", gradeSchema);
